apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: app
          image: europe-west1-docker.pkg.dev/fluent-buckeye-343615/workshop/worker:latest
          envFrom:
            - configMapRef:
                name: kafka-envs
          resources:
            limits:
              cpu: 0.2
              memory: 128Mi
